name: Deploy Infrastructure on AWS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-quality:
    name: Terraform quality code
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.2

      - name: Terraform Init
        id: init
        working-directory: terraform/environments/dev
        run: terraform init

      - name: Terraform Format Check
        id: fmt
        working-directory: terraform/environments/dev
        run: terraform fmt -check

      - name: Terraform Validate
        id: validate
        working-directory: terraform/environments/dev
        run: terraform validate

  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.2

      - name: Terraform Init
        id: init
        working-directory: terraform/environments/dev
        run: terraform init

      - name: Terraform Plan
        id: plan
        working-directory: terraform/environments/dev
        run: terraform plan -input=false
